### ISSUE TITLE
launch crash on my modpack

### ISSUE THREAD

**Issue by netcore10** [enigmartyr/rectified-slabs#3]
client log: https://mclo.gs/UzQFGks
Client crash: https://mclo.gs/N0v6vyD
server crash: https://mclo.gs/7nH7l50

**Comment by Jkmcameron** [comment]
I see errors in betteranimalsplus and alloyforgery but no mention of anything related to my mod in the single log here that is still available. If this was due to my mod it may have been due to my poor management of the server end of things, and may already be fixed. Closing for now but will readdress it if the issue reemerges
